// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw8_C2X2yT0zhPMpoaxYvi4RjqQ_Gd9mY',
    appId: '1:123887658148:web:f01b25414f7935de88b231',
    messagingSenderId: '123887658148',
    projectId: 'twendekazi',
    authDomain: 'twendekazi.firebaseapp.com',
    storageBucket: 'twendekazi.appspot.com',
    measurementId: 'G-VT5M02SRF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0HkCIOm8D0i_uELl1QbHC6LEbZAt_2zo',
    appId: '1:123887658148:android:4f67fcd41a1912ed88b231',
    messagingSenderId: '123887658148',
    projectId: 'twendekazi',
    storageBucket: 'twendekazi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAZO-28BbwvhFJiGqM7jP54nvHAFR19ZI',
    appId: '1:123887658148:ios:272a48128b61b7a488b231',
    messagingSenderId: '123887658148',
    projectId: 'twendekazi',
    storageBucket: 'twendekazi.appspot.com',
    androidClientId: '123887658148-mftlevc9ug0uu30ue2lfv2dsatsk08lh.apps.googleusercontent.com',
    iosClientId: '123887658148-cq5feeenaa216ne83l1h8ju3hes6ug4e.apps.googleusercontent.com',
    iosBundleId: 'com.imotec.twendekazi',
  );
}
